### ISSUE TITLE
a bunch of SSEmpty.unity scenes in Build Settings on Windows.

### ISSUE THREAD

**Issue by hattori** [AnhPham/SSSystem#3]
Everytime when I open a scene attached SSSceneManager.cs in Unity Editor, SSEmpty.unity is added to Build Settings so It ends up with the full of SSEmpty.unity scenes.

At line 1931 of SSSceneManager.cs, string emptyScene = SSFile.GetPathTemplateFile("SSEmpty.unity");

The directory separator in the emptyScene is \(backslash) on Windows OS but one in the scene in EditorBuildSettings.scenes is /(slash) even on Windows OS.
So "if (scene.path.CompareTo(emptyScene) == 0) { return; }" is always failed on Windows OS and SSEmpty.unity is added to the Build Settings.

plz do something like emptyScene = emptyScene.Replace('\\', '/'); at line 1932 to normalize.

Thanks for this great framework !

**Comment by AnhPham** [comment]
I have no Windows laptop or PC to check that bug. Maybe I will install a virtual windows machine. I don't know whether Unity can be installed on a virtual machine.

If you have free time, can you fix that bug then test it for me on the Windows OS? Then please pull a request, I will merge it.

Thank you so much!

**Comment by hattori** [comment]
Done.

**Comment by AnhPham** [comment]
I tested on Mac OS, it worked on Mac OS too.
Thank you so much!
