### ISSUE TITLE
Not issue but question.

### ISSUE THREAD

**Issue by hattori** [AnhPham/SSSystem#5]
I'm kinda wondering where I should put codes to clean up resources used in my popup windows and screens.
I used to disconnect a database connection in the OnDisable method of a derived class of SSController (used as a popup)
but found out the memory was leaking.
That was because the OnDisable method never gets called even though the popup is closed or no matter IsCache flag is true or false.
Thus, I tested which methods are called when they're opened, closed with the IsCache flag is true or false.

■ Opening a popup window using SSSceneManager#PopUp method.

** SSController.IsCache = true

- When the popup is opened for the first time :
Awake
OnSet (data = ...) 
OnFocus (isFocus = True) 
OnShow 

- When the popup is closed :
OnFocus (isFocus = False) 
OnHide 

- When the popup is opened again :
Awake 
OnSet (data = ...) 
OnFocus (isFocus = True) 
OnShow 

** SSController.IsCache = false

- When the popup is opened for the first time :
Awake 
OnSet (data = ...) 
OnFocus (isFocus = True) 
OnShow 

- When the popup is closed :
OnFocus (isFocus = False) 
OnHide 

- When the popup is opened again :
OnSet (data = ...) 
OnFocus (isFocus = True) 
OnShow 

Summary
1. The difference between them is only the Awake method is called or not when the popup is opened again.
2. The Start method of a derived class of SSController is not called even though the derived one overrides the Start method. This is really weird and I don't know why... Do you know ?
3. Disable method never gets called.

■ Opening a screen using SSSceneManager#AddScreen method.

** SSController.IsCache = true

- When the screen is opened for the first time :
Awake
OnEnable
OnSet (data = ...) 
Start
OnEnableFS
OnFocus (isFocus = True) 
OnShow 

- When the screen is closed :
OnFocus (isFocus = False) 
OnHide 
OnDisable

- When the screen is opened again :
OnEnable
OnEnableFS
OnSet (data = ...) 
OnFocus (isFocus = True) 
OnShow 

** SSController.IsCache = false

- When the screen is opened for the first time :
Awake
OnEnable
OnSet (data = ...) 
Start
OnEnableFS
OnFocus (isFocus = True) 
OnShow 

- When the screen is closed :
OnFocus (isFocus = False) 
OnHide 
OnDisable

- When the screen is opened again :
OnEnable
OnEnableFS
OnSet (data = ...) 
OnFocus (isFocus = True) 
OnShow 

Summary
1. They are exactly the same. Doesn't IsCache flag work since the screen is created by AddScreen method ?
2. Start, OnDisable method is called unlike a popup.

So, only Awake, OnFocus, OnShow and OnHide methods are always called in all cases, 
are they the right places to put initialization and cleanup codes you recommend ?

**Comment by AnhPham** [comment]
Sorry for the late reply, I was so busy.

1. About SSController.IsCache,
If cache, when you close the scene, it's root game object will be disabled.
If not, it will be destroyed. So, you see Awake & Start when you try to open your popup again.
(OnDisable will be called on both cases, of course)

2. About AddScreen method.
Imagine you have 3 screens : A, B, C. 
A --click next--> B --click next--> C ( use SSSceneManage.AddScreen )
C --click back--> B--click back-->A ( use SSSceneManage.Close )
Because the B screen must be cached for going back, IsCache has no meaning in case of AddScreen.

**Comment by hattori** [comment]
Thanks for the reply.

I've investigated your framework since I couldn't admit what you say #1. (Start is not called on popup)
And I figured out that SSSystem relies on [ExecuteInEditMode] too much and that caused my problem.
The ExecuteInEditMode is used in the these classes : SSController.cs, SSRoot.cs and SSSceneManager.cs.

Let' say I start the play mode for a scene containing this script in UnityEditor for debugging.
----------------------------------------------------------
public class MyPopup : SSController {
  [SerializeField]
  GameObject myButton; // specified in the inspector.

  public override void Awake() {
    base.Awake ();
    if(...){
      myButton.SetActive(false);
    }
  }
...
-----------------------------------------------------------
Even though I stop the play mode, myButton is still inactive. ( Not only myButton but all scripts and components attached to myButton are also inactive. )
myButton is no longer visible even in edit mode.
This is because SSController uses ExecuteInEditMode so any changes to game object in the play mode remain even after the mode has ended.
SSSystem would change whole settings without my notice ! This is really dangerous.

How can I avoid this ?? or am I missing something ?

Thanks a million.

**Comment by AnhPham** [comment]
You are right! Using [ExecuteInEditMode] is really dangerous for things inside of Awake(), Start(), Update()... which are life cycle methods of MonoBehaviour.

I will try to fix this problem as soon as possible!

I just use ExecuteInEditMode for adding SSRoot to the root game-object automatically. So if you have already SSRoot, you don't need ExecuteInEditMode in SSController anymore.

I recommend you:
- delete [ExecuteInEditMode]  in SSController.
- make a template scene which has already SSRoot in root game-object.
- when you create a new scene, just copy & paste this template scene, then rename.

**Comment by hattori** [comment]
Thanks so much for the quick reply ! :)

I will follow the way you recommend till you fix.

How about SSSceneManager and SSRoot ?? They both use ExecuteInEditMode as well.
I don't think I need to override SSRoot so that is okay.
But I override SSSceneManager as well as your Demo application does so I'm kinda afraid of having the same problem on SSSceneManager.
Please make sure the same problem is NOT caused on SSSceneManager when you fix.
(please fix SSSceneManager too.)

Thanks in advance.

**Comment by hattori** [comment]
Sorry again.

I just let you know SSSManager calls SetActive(false) internally to hide scenes for cache and that causes a big problem as well.
Since SSSManager uses [ExecuteInEditMode], all scripts attached to a scene which applied SetActive(false) are detached.
And when I stop and start the play mode again, scripts will not work since they have been detached from gameobject.

Thanks.

**Comment by AnhPham** [comment]
Sorry for late reply.

I updated SS-System to version 3.0.1.

In 3.0.1, I use  [ExecuteInEditMode] on 2 new scripts named SSAutoSceneManager & SSAutoController, instead of SSSceneManager & SSController.

They are added automatically when you add SSSceneManager or SSController to a game object ( using [RequireComponent] )

After updating to version 3.0.1, you must to add manually SSAutoSceneManager & SSAutoController to your game objects which contains SSSceneManager & SSController, because [RequireComponent] has effect only when you drag a component to game object.

Thank you for your report!

**Comment by hattori** [comment]
Thanks for the update and tips !
It's been working like a charm. So far so good. :)

Thanks a million.
