### ISSUE TITLE
OnShow() method of SSController is called before Awake(), Start() methods.

### ISSUE THREAD

**Issue by hattori** [AnhPham/SSSystem#6]
In my app, OnShow() method of SSSController is called before Awake(), Start() methods so I'm getting null reference error.
( I get a reference to a gameobject in Awake() and use the gameobject in Start() and OnShow()).,

I put logging in your demo app to make sure, then OnShow() is called after Awake() but before Start().

```c#
using UnityEngine;
using System.Collections;

public class DemoScreen1 : SSController
{
    public void OnNextButtonTap()
    {
        SSSceneManager.Instance.AddScreen("DemoScreen2");
    }

	public override void Awake()
	{
		Debug.Log ("Awake *********************************************************");
		base.Awake ();
	}

	public override void Start()
	{
		Debug.Log ("Start *********************************************************");
		base.Start ();
	}

	public override void OnShow()
	{
		Debug.Log ("OnShow *********************************************************");
		base.OnShow ();
	}

}
```

Please fix it so the order is always Awake(), Start() then OnShow()...

Thanks.

**Comment by AnhPham** [comment]
OnShow() is always called after OnSet(), but we don't know the order of OnShow() and Start() in case the scene has no animation.

I recommend you use OnSet() instead of Start().

**Comment by hattori** [comment]
Okay, I got it. I will use OnSet() to setup stuff.
How about cleaning up stuff when the popup is closed ?
Is OnHide() suitable ?

Thanks in advance.

**Comment by AnhPham** [comment]
OnSet(data) almost same OnEnable(), so if you setup stuff in OnSet(data), you should clean them in OnDisable().

By the way, a scene can receive data from other one in OnSet(data), it's useful.

**Comment by hattori** [comment]
Okay. Thanks a lot !
