### ISSUE TITLE
Load scenes from AssetBundle

### ISSUE THREAD

**Issue by hattori** [AnhPham/SSSystem#8]
Hi there,

Unity's official asset, AssetBundle Manager, supports loading a scene from AssetBundle by something like  'yield return StartCoroutine( AssetBundleManager.LoadLevelAsync ("test", "sample", false));'.
https://www.assetstore.unity3d.com/jp/#!/content/45836

Do you have any plans to support AssetBundleManager.LoadLevelAsync(...) to load a scene in SSSystem ?
I wish you will...please :)

Cheers

**Comment by AnhPham** [comment]
Hi,
I have no plan to support AssetBundleManager which is not a build-in feature in Unity.
But you can modify it by yourself. I suggest you modify SSApplication.cs (it's LoadLevel method).

**Comment by hattori** [comment]
Hi,
Okay, I got it.
Thanks !
