### ISSUE TITLE
Weird behavior with Unity 5.5

### ISSUE THREAD

**Issue by hattori** [AnhPham/SSSystem#9]
Hi there,

Let me report a weird behavior I found with Unity 5.5.

https://github.com/AnhPham/SSSystem/blob/1a0ce85fc67eadd6c6dbf181400df90f8117349d/Assets/SSSystem/Scripts/SSRoot.cs#L91

Although the name of the gameobject is updated in Hierarchy of UnityEditor with the code above, it (the name of the gameobject)  is somehow NOT saved internally so SSSystem calls SSApplication#OnLoaded with the gameobject having its old name.
Then it causes "KeyNotFoundException: The given key was not present in the dictionary." at the following code.
https://github.com/AnhPham/SSSystem/blob/1a0ce85fc67eadd6c6dbf181400df90f8117349d/Assets/SSSystem/Scripts/SSApplication.cs#L56

Thanks.

**Comment by AnhPham** [comment]
Thank you for your report. I will check it asap!

**Comment by hattori** [comment]
Update.

It works well if I disable the SSRoot Compoenent of the gameobject before changing its name.
Then I enable the component again after changing its name.

I guess SSRoot causes the problem.

Thanks.

**Comment by AnhPham** [comment]
Thank you so much!
